import Head from 'next/head';

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Privacy Policy — html2apk</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
      </Head>
      <style>{`
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
        :root{--bg:#0d0d0f;--surface:#161618;--border:#2a2a2e;--accent:#7c6af7;--text:#e8e8ec;--muted:#6b6b78;--mono:'JetBrains Mono',monospace;--sans:'Inter',sans-serif}
        body{background:var(--bg);color:var(--text);font-family:var(--sans);min-height:100vh}
        .container{max-width:720px;margin:0 auto;padding:64px 24px 80px}
        .badge{display:inline-block;font-family:var(--mono);font-size:11px;letter-spacing:.12em;color:var(--accent);border:1px solid var(--accent);border-radius:4px;padding:3px 10px;margin-bottom:20px;text-transform:uppercase}
        h1{font-size:2rem;font-weight:600;letter-spacing:-.02em;margin-bottom:8px}
        .updated{font-family:var(--mono);font-size:12px;color:var(--muted);margin-bottom:48px}
        h2{font-size:1.1rem;font-weight:600;margin:36px 0 12px;color:var(--text)}
        p{color:var(--muted);line-height:1.8;margin-bottom:12px;font-size:15px}
        ul{color:var(--muted);line-height:1.8;font-size:15px;padding-left:20px;margin-bottom:12px}
        li{margin-bottom:6px}
        a{color:var(--accent);text-decoration:none}
        a:hover{text-decoration:underline}
        .back{display:inline-block;font-family:var(--mono);font-size:12px;color:var(--accent);margin-bottom:40px;text-decoration:none}
        .back:hover{text-decoration:underline}
        .divider{border:none;border-top:1px solid var(--border);margin:40px 0}
      `}</style>

      <div className="container">
        <a href="/" className="back">← Back to html2apk</a>

        <div className="badge">Legal</div>
        <h1>Privacy Policy</h1>
        <p className="updated">Last updated: August 30, 2026</p>

        <p>
          html2apk ("the Service") is operated by H3cker01. This Privacy Policy explains what information
          is collected when you use the Service and how it is handled.
        </p>

        <h2>1. Information We Collect</h2>
        <p>When you use html2apk, the following data is processed:</p>
        <ul>
          <li><strong>HTML files and code</strong> you upload or paste — used solely to build your APK and discarded after the build completes.</li>
          <li><strong>App configuration inputs</strong> (app name, package name, permissions, signing options) — used only during the build process.</li>
          <li><strong>Icon images</strong> you upload — processed to generate mipmap assets and discarded after the build.</li>
          <li><strong>Keystore files</strong> (if you choose "Use My Key") — used only to sign your APK and never stored persistently.</li>
        </ul>

        <h2>2. Build Data Retention</h2>
        <p>
          APK artifacts generated by the build pipeline are stored temporarily as GitHub Actions artifacts
          with a retention period of <strong>1 day</strong>, after which they are automatically deleted.
          We do not retain your HTML, icon, or keystore files beyond the build process.
        </p>

        <h2>3. Advertising</h2>
        <p>
          The html2apk web platform may display ads served by <strong>Google AdMob</strong> and/or
          <strong>Unity Ads</strong>. These networks may collect certain data in accordance with their
          own privacy policies to serve relevant advertisements:
        </p>
        <ul>
          <li><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google Privacy Policy</a></li>
          <li><a href="https://unity.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Unity Privacy Policy</a></li>
        </ul>
        <p>
          We do not sell your personal information to advertisers or any third parties.
        </p>

        <h2>4. Local Storage</h2>
        <p>
          Build history is stored locally in your browser's <code>localStorage</code>. This data never
          leaves your device and is not transmitted to our servers. You can clear it at any time using
          the "Clear all history" button in the history panel.
        </p>

        <h2>5. Cookies</h2>
        <p>
          The Service itself does not set cookies. Third-party ad networks (AdMob, Unity Ads) may set
          their own cookies in accordance with their respective privacy policies.
        </p>

        <h2>6. Children's Privacy</h2>
        <p>
          The Service is not directed at children under the age of 13. We do not knowingly collect
          personal information from children under 13.
        </p>

        <h2>7. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. The date at the top of this page reflects
          the most recent revision. Continued use of the Service after changes constitutes acceptance of
          the updated policy.
        </p>

        <h2>8. Contact</h2>
        <p>
          If you have questions about this Privacy Policy, you can reach us via the{' '}
          <a href="https://github.com/H3cker01" target="_blank" rel="noopener noreferrer">H3cker01 GitHub profile</a>.
        </p>

        <hr className="divider" />
        <p style={{fontSize:13}}>© 2026 H3cker01 · html2apk</p>
      </div>
    </>
  );
}
